service:
  http_server: on
  http_listener: 0.0.0.0
  http_port: 2020
  log_level: debug
  parsers_file: /fluent-bit/etc/parsers.yaml

pipeline:
  inputs:
    - name: kafka
      brokers: 192.168.10.40:9092
      topics: jamf-mvp.logging.nginx.test.json
      tag: 'docker'
      poll_ms: 100

  filters:
    - name: parser
      match: '*'
      key_name: payload
      parser: docker

  outputs:
    - name: es
      match: '*'
      host: elasticsearch
      port: 9200
      index: 'jamf-mvp.logging.nginx.test.json'
      type: 'nginx'
      tls:   off
      suppress_type_name: on
